### ISSUE TITLE
Openseadragon isn't available in jsDelivr

### ISSUE THREAD

**Issue by rmcloughlin** [webjars/openseadragon#5]
README.md claims: "In addition to being available in the downloadable JAR files, these libraries' files are also accessible through jsDelivr, a free CDN (Content Delivery Network)."  But this isn't true.  See the open request for this here:  https://github.com/openseadragon/openseadragon/issues/372

**Comment by jamesward** [comment]
All WebJars are exposed through jsDelivr automatically, like: https://cdn.jsdelivr.net/webjars/org.webjars/openseadragon/2.2.1/openseadragon.js
